"""Phase 1: local widgets, creative apps, and a simulated email workspace."""
from html import escape
import json

WORKSPACE_PAGES = ['widget-chart','widget-data','chat','portfolio','blog','email-inbox','email-compose','email-read']

PORTFOLIO = [
    {'id':'studio','title':'Studio, with a little soul.','category':'Website','image':'studio','client':'Studio North','year':'2026','description':'Website studio kreatif yang memberi ruang pada karya. Navigasi ringkas, tipografi tebal, dan ritme halaman yang tenang.','deliverables':'Riset, wireframe, UI desktop & mobile, design system'},
    {'id':'forma','title':'Identitas yang berani tampil.','category':'Branding','image':'forma','client':'Forma Objects','year':'2026','description':'Identitas untuk objek sehari-hari yang tidak biasa. Bentuk geometris dan palet hangat menyatukan kemasan, kartu, serta komunikasi digital.','deliverables':'Logo, palet warna, brand guideline, packaging'},
    {'id':'pocket','title':'Keuangan, terasa lebih ringan.','category':'Aplikasi','image':'pocket','client':'Pocket Club','year':'2026','description':'Konsep aplikasi pencatatan keuangan dengan tampilan sederhana. Pengeluaran dan target tabungan bisa dipahami dalam sekali lihat.','deliverables':'User flow, prototype, UI kit, usability notes'},
    {'id':'bloom','title':'Sesuatu yang tumbuh bersamamu.','category':'Branding','image':'bloom','client':'Bloom Market','year':'2026','description':'Sistem visual untuk pasar tanaman lokal. Bentuk organik dipadukan dengan tipografi yang ramah dan warna hijau yang segar.','deliverables':'Brand identity, label produk, social kit'},
    {'id':'mono','title':'Tempat untuk cerita yang baik.','category':'Website','image':'mono','client':'Mono Journal','year':'2026','description':'Eksplorasi publikasi digital yang mengutamakan keterbacaan. Struktur editorial modular memberi ruang bagi berbagai panjang artikel.','deliverables':'Editorial layout, website responsif, komponen artikel'},
    {'id':'move','title':'Ritme baru untuk hari produktif.','category':'Aplikasi','image':'move','client':'Move Together','year':'2026','description':'Dashboard kebiasaan harian untuk kelompok kecil. Progres dirayakan bersama, dengan target yang jelas dan visual yang menyenangkan.','deliverables':'Mobile UI, ilustrasi geometris, prototype interaktif'},
]
ARTICLES = [
    {'id':'ruang','title':'Desain yang berani juga butuh ruang bernapas.','category':'Desain','image':'studio','date':'2026-09-28','read':'4 menit','author':'Nina Sari','excerpt':'Border yang tebal tidak harus berarti tampilan yang ramai. Mulai dari hierarki dan ruang kosong yang sengaja dirancang.','body':['Ruang kosong adalah bagian dari desain. Ia memisahkan informasi, memberi jeda pada mata, dan membantu satu ide tampil jelas sebelum ide berikutnya.','Pada tampilan yang memakai garis tebal, tetapkan satu elemen utama untuk setiap bagian. Biarkan warna aksen mendukung hierarki tersebut, lalu gunakan jarak yang konsisten untuk mengikat semuanya.','Coba mulai dari sketsa hitam-putih. Bila informasi sudah terbaca dengan baik, tambahkan satu warna utama dan dua warna pendamping. Periksa lagi pada layar kecil sebelum menambah dekorasi.']},
    {'id':'token','title':'Dari satu warna ke satu sistem desain.','category':'Workflow','image':'forma','date':'2026-09-25','read':'3 menit','author':'Alex Darma','excerpt':'Token sederhana membantu perubahan kecil terasa konsisten di seluruh produk.','body':['Mulai dari keputusan yang sering berulang: warna teks, warna permukaan, border, radius, dan jarak. Beri nama berdasarkan fungsi, lalu gunakan nama yang sama di setiap komponen.','Sistem kecil yang digunakan dengan konsisten lebih bermanfaat daripada katalog besar yang sulit dipelihara. Dokumentasikan contoh nyata agar setiap anggota tim memahami kapan sebuah komponen dipakai.']},
    {'id':'prototipe','title':'Prototype cepat, pertanyaan yang tepat.','category':'Produk','image':'pocket','date':'2026-09-22','read':'5 menit','author':'Rio Kurnia','excerpt':'Tidak semua hal perlu dibuat sempurna untuk mulai belajar dari pengguna.','body':['Pilih satu pertanyaan sebelum membuat prototype. Apakah pengguna memahami tujuan tombol utama? Apakah urutan langkahnya terasa masuk akal?','Bangun bagian yang diperlukan untuk menjawab pertanyaan itu. Amati tindakan pengguna, catat titik kebingungan, kemudian perbaiki dan ulangi. Detail visual menyusul saat alurnya mulai terbukti.']},
    {'id':'feedback','title':'Feedback yang membawa ide lebih jauh.','category':'Workflow','image':'bloom','date':'2026-09-18','read':'3 menit','author':'Nina Sari','excerpt':'Ubah “kurang cocok” menjadi percakapan tentang tujuan, konteks, dan solusi.','body':['Feedback membantu ketika ia menjelaskan masalah secara spesifik. Sebutkan bagian yang diamati, konteks pemakaian, dan dampaknya bagi pengguna.','Pisahkan masalah dari usulan solusi. Dengan begitu, tim punya ruang untuk menawarkan alternatif yang mungkin lebih sederhana dan efektif.']},
    {'id':'editorial','title':'Membuat halaman panjang tetap nyaman dibaca.','category':'Desain','image':'mono','date':'2026-09-14','read':'4 menit','author':'Alex Darma','excerpt':'Ritme judul, paragraf, dan gambar menentukan perjalanan pembaca.','body':['Halaman editorial bukan hanya kumpulan paragraf. Judul memberi orientasi, gambar membuka konteks, dan jeda memberi kesempatan untuk mencerna informasi.','Jaga panjang baris agar nyaman. Gunakan subjudul yang menjelaskan isi bagian, lalu pastikan pembaca dapat memindai halaman tanpa kehilangan alur cerita.']},
    {'id':'kebiasaan','title':'Rayakan progres kecil setiap hari.','category':'Produk','image':'move','date':'2026-09-10','read':'2 menit','author':'Rio Kurnia','excerpt':'Indikator progres yang baik membuat langkah berikutnya terasa mungkin.','body':['Progres tidak selalu berarti angka yang terus naik. Kadang ia hadir dalam satu keputusan yang lebih jelas atau satu tugas yang akhirnya selesai.','Tampilkan pencapaian dengan konteks. Hindari memaksa pengguna membandingkan dirinya dengan orang lain, dan beri kesempatan untuk menyesuaikan target.']},
]


def data_script(id_, data):
    return f'<script type="application/json" id="{id_}">{json.dumps(data,ensure_ascii=False).replace("<", "\\u003c")}</script>'


def section(title, subtitle, body, cls=''):
    return f'<section class="card {cls}"><div class="card-body"><div class="panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div></div>{body}</div></section>'


def spark(values, kind='line', color='#c4a8f5'):
    xs=[20+i*260/(len(values)-1) for i in range(len(values))]
    points=' '.join(f'{x:.1f},{145-v}' for x,v in zip(xs,values))
    grid=''.join(f'<path d="M20 {y}H280" stroke="#d8d9d1" stroke-dasharray="4 5"/>' for y in [35,85,135])
    if kind=='bar':
        marks=''.join(f'<rect x="{x-10:.1f}" y="{145-v}" width="20" height="{v}" rx="3" fill="{color}" stroke="#232420" stroke-width="2"/>' for x,v in zip(xs,values))
    elif kind=='stacked':
        marks=''.join(f'<rect x="{x-11:.1f}" y="{145-v}" width="22" height="{v}" fill="#c7e8cc" stroke="#232420" stroke-width="2"/><rect x="{x-11:.1f}" y="{145-v-v//2}" width="22" height="{v//2}" fill="#c4a8f5" stroke="#232420" stroke-width="2"/>' for x,v in zip(xs,values))
    else:
        marks=(f'<polygon points="20,145 {points} 280,145" fill="{color}" opacity=".5"/>' if kind=='area' else '')+f'<polyline points="{points}" fill="none" stroke="#232420" stroke-width="3" stroke-linejoin="round"/>'+''.join(f'<circle cx="{x:.1f}" cy="{145-v}" r="4" fill="{color}" stroke="#232420" stroke-width="2"/>' for x,v in zip(xs,values))
    return f'<svg class="mini-chart" viewBox="0 0 300 175" role="img" aria-label="Data contoh berurutan: {", ".join(map(str,values))}">{grid}{marks}<text x="20" y="170">Awal periode</text><text x="280" y="170" text-anchor="end">Akhir periode</text></svg>'


def widget_chart(heading, icon):
    cards=''
    for title,desc,value,kind,color,values in [
        ('Kunjungan website','7 hari terakhir','8.542','line','#c4a8f5',[40,65,52,90,72,105,125]),
        ('Pesanan mingguan','Senin–Minggu','284','bar','#c7e8cc',[45,85,62,100,74,125,95]),
        ('Pertumbuhan pelanggan','Januari–Juni','1.284','area','#ffc7ad',[25,40,36,77,100,125]),
        ('Jam produktif tim','Design (lilac) & development (mint)','216 jam','stacked','#c4a8f5',[55,80,62,75,58,90]),
        ('Konversi harian','7 hari terakhir','4,82%','line','#f9de6e',[28,68,55,91,70,115,108]),
    ]:
        cards+=f'<div class="col-md-6 col-xl-4">{section(title,desc,f"<div class=\"widget-value\">{value}</div>"+spark(values,kind,color),"stat-card h-100")}</div>'
    donut='<div class="donut" role="img" aria-label="Organik 48%, langsung 32%, referral 20%"><div class="donut-hole"><strong>8.542</strong><small>Pengunjung</small></div></div><div class="chart-legend justify-content-center flex-wrap"><span><i class="legend-dot bg-purple"></i>Organik 48%</span><span><i class="legend-dot bg-green"></i>Langsung 32%</span><span><i class="legend-dot bg-yellow"></i>Referral 20%</span></div>'
    cards+=f'<div class="col-md-6 col-xl-4">{section("Sumber traffic","Komposisi kunjungan bulan ini",donut,"stat-card h-100")}</div>'
    return heading('Widget Grafik','Angka yang bercerita. Koleksi grafik mini dengan data ilustratif.','<span class="badge bg-yellow">SVG LOKAL · DATA DEMO</span>')+'<div class="row g-4">'+cards+'</div>'


def widget_data(heading, icon, stats):
    radial='<div class="radial-progress" role="img" aria-label="Target bulanan tercapai 72 persen"><div><strong>72%</strong><small>Target tercapai</small></div></div><p class="text-center small text-muted mb-0">18 dari 25 milestone demo terselesaikan.</p>'
    info='<div class="d-flex gap-3 align-items-center mb-4"><span class="project-icon bg-yellow">'+icon('users')+'</span><div><h3 class="mb-1">Tim kecil. Ide besar.</h3><span class="small text-muted">Creative workspace</span></div></div><div class="avatar-stack mb-4"><span class="avatar bg-purple">AD</span><span class="avatar bg-orange">NS</span><span class="avatar bg-green">RK</span><span class="avatar bg-blue">+5</span></div><p class="small">8 kolaborator, satu ruang untuk menciptakan sesuatu bersama.</p><a href="projects.html" class="btn btn-sm btn-primary">Buka proyek ↗</a>'
    ranking=''.join(f'<div class="mb-4"><div class="d-flex justify-content-between small mb-2"><span>{i}. {name}</span><strong>{value}%</strong></div><div class="progress" role="progressbar" aria-label="Kontribusi {name}" aria-valuenow="{value}" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar bg-{color}" style="width:{value}%"></div></div></div>' for i,(name,value,color) in enumerate([('Nina Sari',92,'purple'),('Alex Darma',84,'green'),('Rio Kurnia',76,'yellow'),('Dina Putri',68,'orange')],1))
    heatmap='<div class="heatmap-grid" role="img" aria-label="Contoh aktivitas 12 minggu. Warna lebih gelap menunjukkan lebih banyak aktivitas.">'+''.join(f'<span class="heat-cell heat-{(i*7+i//4)%5}" title="Hari {i+1}: {(i*7+i//4)%5} aktivitas"></span>' for i in range(84))+'</div><div class="d-flex justify-content-between mt-3 small text-muted"><span>12 minggu terakhir</span><span>Ringan ░ ▒ ▓ Padat</span></div>'
    calendar='<div id="miniCalendar"></div><a href="calendar.html" class="small fw-bold text-dark d-block mt-3">Buka kalender lengkap ↗</a>'
    return heading('Widget Data','Potongan informasi yang membantu kamu melihat gambaran besar.','<span class="badge bg-yellow">DATA ILUSTRATIF</span>')+stats()+'<div class="row g-4">'+''.join(f'<div class="{col}">{section(title,sub,body,"h-100")}</div>' for col,title,sub,body in [('col-md-6 col-xl-4','Target bulan ini','Setiap langkah berarti.',radial),('col-md-6 col-xl-4','Creative crew','Kenali kolaboratormu.',info),('col-md-6 col-xl-4','Kontribusi tim','Progres mingguan contoh.',ranking),('col-lg-7','Ritme kerja','Sedikit progres, setiap hari.',heatmap),('col-lg-5','Kalender mini','Bulan berjalan di perangkatmu.',calendar)])+'</div>'


def chat(heading, icon):
    return heading('Percakapan yang menggerakkan ide.','Ruang kecil untuk bertukar kabar dengan tim.','<span class="badge bg-green">WORKSPACE CHAT</span>')+'''<div class="card chat-app"><aside class="chat-contacts" aria-label="Percakapan"><div class="p-4 border-bottom"><h2>Pesan tim</h2><label class="visually-hidden" for="chatSearch">Cari percakapan</label><input id="chatSearch" type="search" class="form-control mt-3" placeholder="Cari nama…"></div><div id="chatContacts"></div></aside><section class="chat-conversation" aria-label="Percakapan aktif"><header id="chatHeader" class="chat-header"></header><div id="chatMessages" class="chat-messages" role="log" aria-live="polite" aria-label="Riwayat pesan"></div><form id="chatForm" class="chat-composer"><label class="visually-hidden" for="chatInput">Pesan baru</label><textarea id="chatInput" class="form-control" rows="2" maxlength="2000" placeholder="Tulis pesan untuk tim…" required></textarea><button class="btn btn-primary" type="submit">Kirim ↗</button></form><p class="chat-demo-note">Demo lokal · Pesan tersimpan di browser dan tidak dikirim ke pengguna lain.</p></section></div>'''


def detail_modal(id_, title_id):
    return f'<div class="modal fade" id="{id_}" tabindex="-1" aria-labelledby="{title_id}" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h2 class="modal-title" id="{title_id}"></h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup detail"></button></div><div class="modal-body" id="{id_}Body"></div></div></div></div>'


def portfolio(heading, icon):
    cards=''.join(f'<article class="card portfolio-card" data-portfolio-category="{p["category"]}"><img src="assets/img/workspace/{p["image"]}.svg" alt="Konsep desain {escape(p["client"])}" width="720" height="480"><div class="card-body"><div class="d-flex justify-content-between mb-3"><span class="badge bg-yellow">{p["category"]}</span><span class="eyebrow text-muted">{p["year"]}</span></div><h2>{p["title"]}</h2><p class="small text-muted">{p["client"]}</p><a class="portfolio-detail text-dark fw-bold small" href="#project-{p["id"]}" data-project-detail="{p["id"]}">Lihat studi kasus ↗</a></div></article>' for p in PORTFOLIO)
    filters=''.join(f'<button class="btn btn-sm {"btn-dark" if i==0 else "btn-outline-primary"}" data-portfolio-filter="{label}" aria-pressed="{"true" if i==0 else "false"}">{label}</button>' for i,label in enumerate(['Semua','Website','Branding','Aplikasi']))
    return heading('Ide yang sudah jadi nyata.','Koleksi karya demo dari creative workspace kita.','<a class="btn btn-primary" href="projects.html">'+icon('folder')+' Workspace proyek</a>')+'<div class="portfolio-intro bg-purple"><span class="eyebrow">SELECTED WORK / 2026</span><h2>Berbeda itu<br>bagian dari proses.</h2><p>Eksplorasi bentuk, warna, dan pengalaman digital.<br>Enam konsep. Banyak kemungkinan.</p><span aria-hidden="true">✳</span></div><div class="d-flex flex-wrap gap-2 mb-4" role="group" aria-label="Filter portfolio">'+filters+'</div><p id="portfolioCount" class="small text-muted" aria-live="polite">6 karya</p><div class="portfolio-grid">'+cards+'</div>'+detail_modal('portfolioModal','portfolioTitle')+data_script('portfolioData',PORTFOLIO)


def blog(heading, icon):
    cards=''.join(f'<article class="card blog-card" data-article-id="{p["id"]}"><img src="assets/img/workspace/{p["image"]}.svg" alt="Ilustrasi geometris artikel {escape(p["title"])}" width="720" height="480"><div class="card-body"><div class="d-flex gap-3 align-items-center mb-3"><span class="badge bg-green">{p["category"]}</span><time class="small text-muted" datetime="{p["date"]}">{p["date"]}</time></div><h2><a href="#article-{p["id"]}" data-article-detail="{p["id"]}">{p["title"]}</a></h2><p class="small text-muted">{p["excerpt"]}</p><div class="d-flex justify-content-between align-items-center small gap-2"><span>{p["author"]} · {p["read"]}</span><a class="fw-bold text-dark" href="#article-{p["id"]}" data-article-detail="{p["id"]}">Baca ↗</a></div></div></article>' for p in ARTICLES)
    filters=''.join(f'<button class="list-group-item list-group-item-action {"active" if i==0 else ""}" data-blog-category="{label}" aria-pressed="{"true" if i==0 else "false"}">{label}</button>' for i,label in enumerate(['Semua','Desain','Workflow','Produk']))
    sidebar=section('Temukan cerita','Apa yang sedang kamu pikirkan?','<label for="blogSearch" class="visually-hidden">Cari artikel</label><input id="blogSearch" class="form-control" type="search" placeholder="Cari judul atau topik…">')+section('Kategori','Pilih sudut pandangmu.','<div class="list-group" role="group" aria-label="Kategori artikel">'+filters+'</div>')+section('Catatan dari studio','Ide kecil untuk minggu ini.','<p class="fs-5 fw-bold">Beri ruang untuk mencoba sesuatu yang belum pernah kamu buat.</p><a href="portfolio.html" class="btn btn-sm btn-dark">Cari inspirasi ↗</a>','bg-yellow')
    return heading('Catatan dari balik layar.','Tentang desain, proses, dan hal-hal kecil yang membuat produk lebih baik.')+'<div class="blog-layout"><div><div id="blogArticles" class="d-grid gap-4">'+cards+'</div><p id="blogCount" class="small text-muted mt-4" aria-live="polite"></p><nav aria-label="Halaman artikel"><ul class="pagination gap-2" id="blogPagination"></ul></nav></div><aside class="blog-sidebar" aria-label="Filter dan informasi blog">'+sidebar+'</aside></div>'+detail_modal('articleModal','articleTitle')+data_script('articleData',ARTICLES)


FOLDERS=[('inbox','Kotak masuk'),('starred','Berbintang'),('sent','Terkirim'),('draft','Draft'),('spam','Spam'),('trash','Sampah')]


def mail_shell(body, icon):
    nav=''.join(f'<a class="mail-folder" href="email-inbox.html?folder={slug}" data-mail-folder="{slug}"><span>{label}</span><span class="badge bg-yellow" data-folder-count="{slug}">0</span></a>' for slug,label in FOLDERS)
    return '<div class="mail-layout"><aside class="mail-sidebar card no-print" aria-label="Folder email"><div class="card-body"><a class="btn btn-primary w-100 mb-4" href="email-compose.html">'+icon('plus')+' Tulis pesan</a><nav>'+nav+'</nav><div class="mail-account"><span class="avatar bg-purple">AD</span><div><strong>Alex Darma</strong><small>alex@example.com</small></div></div><p class="small text-muted mb-0">Mailbox demo lokal. Tidak terhubung ke layanan email.</p></div></aside><section class="card mail-content">'+body+'</section></div>'


def inbox(heading, icon):
    body='''<div class="card-header"><div class="panel-heading mb-3"><div><h2 id="mailFolderTitle">Kotak masuk</h2><p>Semua kabar, satu tempat.</p></div><span class="badge bg-green">DEMO</span></div><label class="visually-hidden" for="mailSearch">Cari email</label><input class="form-control" id="mailSearch" type="search" placeholder="Cari pengirim, subjek, atau isi…"></div><div class="mail-toolbar"><label class="d-flex align-items-center gap-2 small"><input class="form-check-input m-0" id="mailSelectAll" type="checkbox">Pilih semua</label><div class="d-flex flex-wrap gap-2"><button type="button" class="btn btn-sm" id="mailMarkRead" disabled>Tandai dibaca</button><button type="button" class="btn btn-sm btn-danger" id="mailTrash" disabled>Ke sampah</button><button type="button" class="btn btn-sm btn-success" id="mailRestore" hidden disabled>Pulihkan</button></div></div><div id="mailNotice" class="mx-4 mt-3 small" role="status"></div><div id="mailRows"></div><div class="card-footer"><small id="mailCount" aria-live="polite"></small></div>'''
    return heading('Kabar baik dimulai di sini.','Kelola pesan dan percakapan dalam mailbox demo kamu.')+mail_shell(body,icon)


def compose(heading, icon):
    body='''<div class="card-header"><h2 class="mb-0">Pesan baru</h2></div><form id="mailComposeForm"><div class="card-body"><div class="row g-3"><div class="col-12"><label class="form-label" for="mailTo">Kepada</label><input id="mailTo" name="to" class="form-control" type="email" multiple placeholder="nina@example.com" required maxlength="300"></div><div class="col-md-6"><label class="form-label" for="mailCc">CC <span class="text-muted">(opsional)</span></label><input id="mailCc" name="cc" class="form-control" type="email" multiple maxlength="300"></div><div class="col-md-6"><label class="form-label" for="mailBcc">BCC <span class="text-muted">(opsional)</span></label><input id="mailBcc" name="bcc" class="form-control" type="email" multiple maxlength="300"></div><div class="col-12"><label class="form-label" for="mailSubject">Subjek</label><input id="mailSubject" name="subject" class="form-control" required maxlength="160" placeholder="Satu ide untuk proyek berikutnya…"></div><div class="col-12"><label class="form-label" for="mailBody">Isi pesan</label><div class="format-preview" aria-label="Contoh toolbar formatting"><button type="button" disabled aria-label="Bold (contoh visual)"><strong>B</strong></button><button type="button" disabled aria-label="Italic (contoh visual)"><em>I</em></button><button type="button" disabled aria-label="Underline (contoh visual)"><u>U</u></button><small>Toolbar contoh · isi pesan berupa teks biasa</small></div><textarea id="mailBody" name="body" class="form-control" rows="10" required maxlength="10000" placeholder="Halo tim,\n\nAku punya ide…"></textarea></div></div><p class="small text-muted mt-3 mb-0">Kirim demo menyimpan pesan ke folder Terkirim di browser ini. Tidak ada email yang dikirim ke alamat penerima.</p><p id="composeStatus" class="small mt-3 mb-0" role="status"></p></div><div class="card-footer d-flex flex-wrap gap-3"><button type="submit" class="btn btn-primary">Kirim demo ↗</button><button type="button" class="btn" id="mailSaveDraft">Simpan draft</button><button type="button" class="btn btn-outline-danger ms-sm-auto" data-bs-toggle="modal" data-bs-target="#discardMailModal">Buang</button></div></form>'''
    modal='''<div class="modal fade" id="discardMailModal" tabindex="-1" aria-labelledby="discardMailTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title" id="discardMailTitle">Buang pesan ini?</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button></div><div class="modal-body">Isi pesan akan dikosongkan. Draft yang sudah disimpan akan dipindahkan ke Sampah.</div><div class="modal-footer"><button type="button" class="btn" data-bs-dismiss="modal">Batal</button><button type="button" class="btn btn-danger" id="mailDiscard">Ya, buang pesan</button></div></div></div></div>'''
    return heading('Satu pesan. Banyak kemungkinan.','Tulis kabar yang ingin kamu bagikan kepada tim.')+mail_shell(body,icon)+modal


def read_mail(heading, icon):
    return heading('Ruang untuk percakapan.','Baca detail pesan dan lanjutkan diskusinya.','<a class="btn no-print" href="email-inbox.html">← Kotak masuk</a>')+mail_shell('<div id="mailReadContent" class="card-body mail-reader"></div>',icon)


def build_workspace_pages(heading, icon, stats):
    return {'widget-chart':widget_chart(heading,icon),'widget-data':widget_data(heading,icon,stats),'chat':chat(heading,icon),'portfolio':portfolio(heading,icon),'blog':blog(heading,icon),'email-inbox':inbox(heading,icon),'email-compose':compose(heading,icon),'email-read':read_mail(heading,icon)}


def write_workspace_assets(root):
    folder=root/'assets/img/workspace'; folder.mkdir(parents=True,exist_ok=True)
    artwork={
        'studio':('#c4a8f5','<rect x="130" y="92" width="480" height="310" rx="12" fill="#232420"/><rect x="114" y="76" width="480" height="310" rx="12" fill="#fffefb" stroke="#232420" stroke-width="5"/><path d="M114 124h480" stroke="#232420" stroke-width="5"/><circle cx="141" cy="101" r="6"/><circle cx="165" cy="101" r="6"/><text x="150" y="220" font-size="62" font-weight="900">STUDIO.</text><text x="153" y="261" font-size="19">A LITTLE DIFFERENT.</text><rect x="152" y="290" width="170" height="44" fill="#f9de6e" stroke="#232420" stroke-width="3"/><path d="m472 166 15 46 49-5-37 32 20 44-43-24-35 35 9-49-47-19 49-7z" fill="#c7e8cc" stroke="#232420" stroke-width="4"/>'),
        'forma':('#ffc7ad','<rect x="145" y="70" width="290" height="335" fill="#232420"/><rect x="130" y="55" width="290" height="335" fill="#f9de6e" stroke="#232420" stroke-width="5"/><text x="154" y="139" font-size="58" font-weight="900">FORMA</text><circle cx="275" cy="253" r="76" fill="#c4a8f5" stroke="#232420" stroke-width="5"/><path d="m250 299 78-82v82z" fill="#232420"/><rect x="374" y="244" width="225" height="132" rx="8" fill="#fffefb" stroke="#232420" stroke-width="5"/><text x="397" y="309" font-size="32" font-weight="800">f.</text><path d="M397 333h172" stroke="#232420" stroke-width="3"/>'),
        'pocket':('#c1dff4','<rect x="254" y="42" width="228" height="410" rx="36" fill="#232420"/><rect x="238" y="28" width="228" height="410" rx="36" fill="#fffefb" stroke="#232420" stroke-width="5"/><path d="M310 49h82" stroke="#232420" stroke-width="8" stroke-linecap="round"/><text x="263" y="109" font-size="26" font-weight="800">pocket.</text><rect x="258" y="133" width="188" height="120" rx="12" fill="#c7e8cc" stroke="#232420" stroke-width="3"/><text x="275" y="175" font-size="15">SAVINGS, BUT FUN.</text><text x="275" y="214" font-size="29" font-weight="800">Rp8,4 jt</text><path d="M267 297h166m-166 42h166m-166 42h108" stroke="#232420" stroke-width="5"/>'),
        'bloom':('#c7e8cc','<rect x="155" y="93" width="420" height="307" fill="#232420"/><rect x="140" y="78" width="420" height="307" fill="#fffefb" stroke="#232420" stroke-width="5"/><path d="M350 252v73m0-73c-70 0-84-90-84-90s82 0 84 90zm0 0c75 0 89-103 89-103s-83 12-89 103z" fill="#c7e8cc" stroke="#232420" stroke-width="5"/><text x="183" y="143" font-size="41" font-weight="900">BLOOM MARKET</text><text x="188" y="354" font-size="18">GROW AT YOUR OWN PACE.</text>'),
        'mono':('#f9de6e','<rect x="151" y="63" width="440" height="360" fill="#232420"/><rect x="136" y="48" width="440" height="360" fill="#fffefb" stroke="#232420" stroke-width="5"/><text x="165" y="119" font-size="58" font-weight="900">MONO.</text><path d="M165 143h380" stroke="#232420" stroke-width="3"/><rect x="165" y="168" width="181" height="203" fill="#c4a8f5" stroke="#232420" stroke-width="3"/><circle cx="256" cy="271" r="63" fill="#ffc7ad" stroke="#232420" stroke-width="3"/><path d="M369 182h176m-176 30h155m-155 30h176m-176 58h176m-176 30h155m-155 30h135" stroke="#232420" stroke-width="6"/>'),
        'move':('#f4a8c4','<rect x="107" y="99" width="525" height="310" rx="16" fill="#232420"/><rect x="92" y="84" width="525" height="310" rx="16" fill="#fffefb" stroke="#232420" stroke-width="5"/><text x="125" y="145" font-size="34" font-weight="900">MAKE YOUR MOVE.</text><circle cx="226" cy="267" r="78" fill="#c4a8f5" stroke="#232420" stroke-width="4"/><circle cx="226" cy="267" r="49" fill="#fffefb" stroke="#232420" stroke-width="4"/><text x="190" y="280" font-size="28" font-weight="800">72%</text><rect x="348" y="196" width="211" height="45" fill="#c7e8cc" stroke="#232420" stroke-width="3"/><rect x="348" y="260" width="164" height="31" fill="#f9de6e" stroke="#232420" stroke-width="3"/><rect x="348" y="312" width="190" height="31" fill="#ffc7ad" stroke="#232420" stroke-width="3"/>'),
    }
    for name,(color,shapes) in artwork.items():
        (folder/f'{name}.svg').write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 480"><rect width="720" height="480" fill="{color}"/><g fill="#232420" font-family="Arial, sans-serif">{shapes}</g></svg>',encoding='utf-8')
